---
title: "The Start of My Research Career"
date: 2026-01-10
categories: ["Research", "Experiences"]
description: ""
author: "Aashik Bhalodia"
---

## Baltimore

At Johns Hopkins, I pursued a really broad range of academic and extracurricular experiences which ultimately led to me catching the research bug. 

My first research experience was just before the pandemic in the lab of Dr. Anne Murphy studying pediatric cardiomyopathy. My time here was cut short due to the pandemic, but it nonetheless started my research journey. 

When I was able to return to lab, I joined Dr. Luigi Adamo's lab studying cardiac immunology. I had serendipitously seen his engaging talk at JHU years before and was lucky enough to join his new lab and continue research for the next 3 years. The lab was specifically interested in the role of B cells in cardiac homeostasis and in various cardiac pathologies. We used mouse models of cardiac injury (MI & TAC) and B cell deficiency (K.O. & depletions) to understand the mechanism by which B cells modulated cardiac function. The lab primarily employed histology (H&E, trichrome), echocardiography, and telemetry to measure cardiac function. As the youngest member of the team, I had the amazing opportunity to learn from the rest of the lab who had tremendous experience in different fields, ranging from basic science to clinical medicine, in addition to our lab manager Sylvie who showed me how a lab functions behind the scenes and how to run my first mouse experiments. 

I truly owe it to my amazing post-doc mentors Kevin and Charlie and my wonderful PI Luigi for my love of biomedical research and for inspiring me to attend graduate school. I'll never forget the espresso and fun lab outings in town. 

## New Haven

I am so thankful for the advice to remain open about my field of study during my PhD because I would not have ended up researching the fascinating non-coding genome. Graduate school was a new opportunity for me to learn a different field of biomedicine after spending the last 3 years in cardiology. At Yale, I entered through the Translational Molecular Medicine, Pharmacology, and Physiology first year track in addition to being selected for the Medical Research Scholars T32 Training Program. Coursework and lab rotations my first year greatly helped ease my transition to graduate school.